Repository pavelzw/Analysis-I-Skript, pull requests merged in 2019-01, with the labels that each got.

#27 Codestyleverbesserungen
  ana1.tex
  ana1short.tex
  ana1ü.tex
  chapters/chapter10.tex
  chapters/chapter11.tex
  chapters/chapter12.tex
  chapters/chapter2.tex
  chapters/chapter3.tex
  chapters/chapter7.tex
  chapters/chapter8.tex
  chapters/chapter9.tex
Labels: enhancement

#28 Codestyleverbesserungen
  chapters/chapter1.tex
  chapters/chapter3.tex
  chapters/chapter4.tex
  chapters/chapter5.tex
  chapters/chapter6.tex
Labels: enhancement

#29 Übungen 09.11.18, 16.11.18
  ana1short.synctex(busy)
  ana1ü.tex
Labels: continuation

#30 Vorlesung vom 08.01.2019
  ana1.tex
  ana1short.synctex(busy)
  ana1short.tex
  chapters/chapter1.tex
  chapters/chapter12.tex
  chapters/chapter13.tex
  chapters/test.tex
  skript.sty
Labels: continuation, enhancement

#31 Vorlesung vom 10.01.2019, Übung aufgeräumt
  .gitignore
  ana1.tex
  ana1u.tex
  ana1ü.tex
  chapters/chapter13.tex
  chapters/chapter14.tex
  chapters_uebung/chapter1u.tex
  chapters_uebung/chapter2u.tex
  chapters_uebung/chapter3u.tex
  chapters_uebung/chapter4u.tex
  chapters_uebung/chapter5u.tex
  chapters_uebung/chapter6u.tex
  chapters_uebung/chapter7u.tex
  chapters_uebung/chapter8u.tex
  skript.sty
Labels: continuation, enhancement

#32 Vorlesung vom 11.01.2019
  chapters/chapter13.tex
  chapters/chapter14.tex
  skript.sty
Labels: continuation, enhancement

#33 fehler in Kapitel 7 behoben
  chapters/chapter7.tex
Labels: enhancement

#34 Verbesserungen Chapter 12
  chapters/chapter12.tex
  skript.sty
Labels: enhancement

#35 Verbesserungen Chapter 14
  chapters/chapter14.tex
  chapters/chapter7.tex
Labels: enhancement

#36 behebt fehler in chapter13.tex
  chapters/chapter13.tex
Labels: enhancement

#37 Vorlesung vom 15.01.2019
  ana1.tex
  chapters/chapter14.tex
  chapters/chapter15.tex
  chapters/chapter3.tex
  chapters/chapter4.tex
  skript.sty
Labels: continuation, enhancement

#38 Vorlesungsmitschrieb vom 17.01.2018
  ana1.tex
  ana1short.tex
  chapters/chapter15.tex
  chapters/chapter16.tex
  skript.sty
Labels: continuation

#39 Anashort
  ana1.tex
  ana1short.tex
  skript.sty
Labels: enhancement

#40 behebt kleinere Rechtschreibfehler
  chapters/chapter13.tex
  chapters/chapter14.tex
  chapters/chapter16.tex
  chapters/chapter3.tex
Labels: enhancement

#41 Vorlesung vom 22.01.2019
  ana1.tex
  ana1short.tex
  chapters/chapter15.tex
  chapters/chapter16.tex
  chapters/chapter17.tex
Labels: continuation, enhancement

#42 Vorlesungsmitschrieb vom 24.01.2019
  chapters/chapter17.tex
  skript.sty
Labels: continuation, enhancement

#43 Vorlesungs Zusatz vom 25.01.19
  chapters/chapter15.tex
  chapters/chapter16.tex
  chapters/chapter17.tex
Labels: continuation, enhancement

#45 Übung 11.01.19
  ana1u.tex
  chapters/chapter14.tex
  chapters/chapter16.tex
  chapters_uebung/chapter2u.tex
  chapters_uebung/chapter3u.tex
  chapters_uebung/chapter4u.tex
  chapters_uebung/chapter5u.tex
  chapters_uebung/chapter6u.tex
  chapters_uebung/chapter7u.tex
  chapters_uebung/chapter8u.tex
  chapters_uebung/chapter9u.tex
Labels: continuation, enhancement

#44 Verbesserungen
  .gitignore
  ana-skript.bib
  ana1.tex
  chapters/chapter2.tex
  chapters/chapter3.tex
  chapters/chapter4.tex
  skript.sty
Labels: enhancement

#46 Jannis
  .gitignore
  ana1.tex
  ana1u.tex
  chapters/chapter10.tex
  chapters/chapter11.tex
  chapters/chapter12.tex
  chapters/chapter13.tex
  chapters/chapter14.tex
  chapters/chapter15.tex
  chapters/chapter16.tex
  chapters/chapter17.tex
  chapters/chapter2.tex
  chapters/chapter3.tex
  chapters/chapter4.tex
  chapters/chapter5.tex
  chapters/chapter6.tex
  chapters/chapter7.tex
  chapters/chapter8.tex
  chapters/chapter9.tex
  skript.sty
Labels: enhancement

#47 Vorlesung vom 29.01.2019 und 31.01.2019
  ana1.tex
  ana1u.tex
  chapters/chapter17.tex
  chapters/chapter18.tex
  chapters/chapter19.tex
  skript.sty
Labels: continuation, enhancement
