Repository pavelzw/Analysis-I-Skript, pull requests merged in 2019-02, with the labels that each got.

#49 Vorlesungsmitschrieb vom 01.02.2019
  chapters/chapter19.tex
  skript.sty
Labels: continuation

#50 Übung 18.01.19
  ana1u.tex
  chapters/chapter18.tex
  chapters_uebung/chapter10u.tex
Labels: continuation, enhancement

#52 Vorlesung 05.02.19
  ana1.tex
  chapters/chapter18.tex
  chapters/chapter19.tex
  chapters/chapter20.tex
Labels: continuation

#53 Vorlesung vom 07.02.2019
  ana1.tex
  chapters/chapter18.tex
  chapters/chapter19.tex
  chapters/chapter20.tex
  chapters_uebung/chapter11u.tex
Labels: continuation, enhancement

#55 Korrekturen
  ana1.tex
  chapters/chapter18.tex
  chapters/chapter2.tex
  chapters/chapter20.tex
  chapters/chapter3.tex
  chapters/chapter4.tex
  chapters/chapter5.tex
  chapters/chapter6.tex
  chapters/chapter7.tex
  chapters/chapter8.tex
  chapters/chapter9.tex
  skript.sty
Labels: enhancement
